name: Auto sync forked repo
on:
  schedule:
    - cron: '55 23 * * *' # runs at 11:55 pm
  push:
    branches: 
      - master

jobs:
  Github_Workflow_Sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync and merge upstream repository with your current repository
        uses: dabreadman/sync-upstream-repo@v1.0.0.b 
        with:
          upstream_repo: "https://github.com/simranlotey/programs.git"
          upstream_branch: master
          downstream_branch: master
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

